#!/usr/bin/env bash
# This script displays "Best School" and "Hi" under certain conditions

counter=0
while[[ counter -lt 10 ]]  
do
        if [[ counter -eq 8 ]]; then  
                echo "Hi"
                (( counter++ ))  
                continue
        fi
        echo "Best School"
        (( counter++ ))  
done

