#!/bin/env bash
# Counter to keep track of loop iterations
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
