#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=0
while [[ counter -lt 10 ]]
do
	if [[ counter -eq 4 ]];then
		echo "bad luck"
		(( counter++ ))
		continue
	elif [[ counter -eq 8 ]];then
		echo "good luck"
		(( counter++ ))
		continue
	else
	echo "Best School"
	(( counter++ ))
	fi
done
